"""init schema

Revision ID: 83ddc61c4e9d
Revises: 
Create Date: 2026-04-04 18:38:15.921466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ddc61c4e9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('prev_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('change', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('change_percent', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('lot_size', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_ticker'), 'quotes', ['ticker'], unique=False)
    op.create_index(op.f('ix_quotes_update_time'), 'quotes', ['update_time'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_quotes_update_time'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_ticker'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
